# Konfigurasi Continuos Deployment
name: 1_pharmacy

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy 1_pharmacy API with github action
        uses: appleboy/ssh-action@master
        with:
          host: 172.105.115.129
          username: "root"
          password: "PurwadhikaJCWD;"
          port: 22
          script: |
            cd ~/app/1-pharmacy-api
            git pull origin master
            npm install
            pm2 restart 1-pharmacy
